"""add time column to workout, remove time from exercise

Revision ID: 1d4fbb5f2067
Revises: ab55989dced6
Create Date: 2023-08-26 10:37:33.581259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4fbb5f2067'
down_revision = 'ab55989dced6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'time')
    op.add_column('workouts', sa.Column('time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'time')
    op.add_column('exercises', sa.Column('time', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
