"""add time column

Revision ID: ab55989dced6
Revises: 1a0e5ff8f67f
Create Date: 2023-08-26 10:34:47.052792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab55989dced6'
down_revision = '1a0e5ff8f67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'time')
    # ### end Alembic commands ###
